name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 需要完整历史来获取提交记录
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Compile TypeScript
        run: npm run compile
        
      - name: Install vsce
        run: npm install -g @vscode/vsce
        
      - name: Build VSIX
        run: vsce package
        
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Get previous tag
        id: get_previous_tag
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
          
      - name: Get commit history
        id: get_commits
        run: |
          if [ -n "${{ steps.get_previous_tag.outputs.PREVIOUS_TAG }}" ]; then
            COMMITS=$(git log ${{ steps.get_previous_tag.outputs.PREVIOUS_TAG }}..HEAD --oneline)
          else
            COMMITS=$(git log --oneline | head -20)
          fi
          echo "COMMITS<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Generate changelog with Claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          direct_prompt: |
            Generate a concise changelog based on the following git commits.
            
            Commits:
            ${{ steps.get_commits.outputs.COMMITS }}
            
            Use the following format:
            ### ✨ New Features
            - Feature description
            
            ### 🐛 Bug Fixes
            - Fix description
            
            ### 🔧 Improvements
            - Improvement description
            
            Only include sections that have actual changes. Save the result to a file named changelog.md.
          allowed_tools: "Write"
          
      - name: Read changelog
        id: read_changelog
        run: |
          if [ -f changelog.md ]; then
            echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
            cat changelog.md >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "CHANGELOG=" >> $GITHUB_OUTPUT
          fi
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.vsix'
          generate_release_notes: true
          name: Release v${{ steps.get_version.outputs.VERSION }}
          body: |
            ## 🎉 Kiro for Claude Code v${{ steps.get_version.outputs.VERSION }}
            
            ${{ steps.read_changelog.outputs.CHANGELOG }}
            
            ### Installation
            
            **From Extension Marketplace:**
            ```bash
            # VSCode (from VSCode Marketplace)
            code --install-extension heisebaiyun.kiro-for-cc
            
            # Cursor (from OpenVSX)
            cursor --install-extension heisebaiyun.kiro-for-cc
            ```
            
            **From VSIX file:**
            Download the `.vsix` file from assets below and install:
            ```bash
            # VSCode
            code --install-extension kiro-for-cc-${{ steps.get_version.outputs.VERSION }}.vsix
            
            # Cursor
            cursor --install-extension kiro-for-cc-${{ steps.get_version.outputs.VERSION }}.vsix
            ```
            
            ### Links
            - [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=heisebaiyun.kiro-for-cc)
            - [OpenVSX Registry](https://open-vsx.org/extension/heisebaiyun/kiro-for-cc)
            - [Documentation](https://github.com/notdp/kiro-for-cc#readme)
            
            ---
            See below for auto-generated release notes.
      
      - name: Publish to VSCode Marketplace
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
        continue-on-error: true
      
      - name: Install ovsx
        run: npm install -g ovsx
        
      - name: Create OpenVSX namespace (if needed)
        run: |
          ovsx create-namespace heisebaiyun -p ${{ secrets.OVSX_PAT }} || echo "Namespace already exists"
        continue-on-error: true
        
      - name: Publish to OpenVSX
        run: ovsx publish -p ${{ secrets.OVSX_PAT }}
        continue-on-error: true